import { Product } from "./types";

export const CATEGORIES = [
  { id: 1, name: "Vehicles", icon: "🚗", count: 17801 },
  { id: 2, name: "Property", icon: "🏠", count: 19563 },
  { id: 3, name: "Mobile Phones & Tablets", icon: "📱", count: 35559 },
  { id: 4, name: "Electronics", icon: "💻", count: 359665 },
  { id: 5, name: "Home, Furniture & Appliances", icon: "🛋️", count: 57843 },
  { id: 6, name: "Fashion", icon: "👗", count: 40381 },
  { id: 7, name: "Beauty & Personal Care", icon: "💄", count: 36439 },
  { id: 8, name: "Services", icon: "🔧", count: 2441 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "New OnePlus 9 256 GB Blue",
    price: 26000,
    location: "Addis Ababa, Addis Ketema",
    image: "/images/oneplus-9.jpg",
    condition: "Brand New",
    seller: "TechHub Store",
    verified: true,
    rating: 4.8,
    description:
      "OnePlus 9 in pristine condition. 256GB storage, 8GB RAM, original charger included. Fast performance and excellent camera.",
    category: 3,
  },
  {
    id: 2,
    title: "New Xiaomi Redmi Note 9 Pro 128 GB Blue",
    price: 17000,
    location: "Addis Ababa, Bole",
    image: "/images/redmi-note-9.jpg",
    condition: "Brand New",
    seller: "Mobile Express",
    verified: true,
    rating: 4.9,
    category: 3,
  },
  {
    id: 3,
    title: "Apple iPhone X 64 GB Black",
    price: 15000,
    location: "Addis Ababa, Yeka",
    image: "/images/iphone-x.jpg",
    condition: "Used",
    seller: "Prime Phones",
    rating: 4.7,
    category: 3,
  },
  {
    id: 4,
    title: "Samsung Galaxy S10 Lite 128 GB Black",
    price: 12500,
    location: "Addis Ababa, Addis Ketema",
    image: "/images/galaxy-s10.jpg",
    condition: "Used",
    seller: "Galaxy Store",
    rating: 4.6,
    category: 3,
  },
  {
    id: 5,
    title: "Toyota Corolla 1.6 (Used)",
    price: 1800000,
    location: "Addis Ababa, Nifas Silk",
    image: "/images/toyota-corolla.jpg",
    condition: "Used",
    seller: "Sofia D.",
    rating: 5.0,
    description:
      "Well maintained Toyota Corolla 1.6, single owner, full service history, excellent tyres and interior.",
    category: 1,
  },
  {
    id: 6,
    title: "Honda Civic 2015",
    price: 1600000,
    location: "Addis Ababa, Bole",
    image: "/images/honda-civic.jpg",
    condition: "Used",
    seller: "Daniel K.",
    rating: 4.6,
    category: 1,
  },
  {
    id: 7,
    title: "Winter Jacket",
    price: 2500,
    location: "Addis Ababa, Kirkos",
    image: "/images/winter-jacket.jpg",
    condition: "Brand New",
    seller: "Fashion Store",
    rating: 4.8,
    category: 6,
  },
  {
    id: 8,
    title: "LED Ring Light",
    price: 1800,
    location: "Addis Ababa, Piazza",
    image: "/images/led-ring-light.jpg",
    condition: "Brand New",
    seller: "Photo Studio",
    rating: 4.9,
    category: 4,
  },
  {
    id: 9,
    title: "MacBook Pro 16-inch M1",
    price: 85000,
    location: "Addis Ababa, Bole",
    image: "/images/macbook-pro.jpg",
    condition: "Brand New",
    seller: "Apple Authorized",
    rating: 5.0,
    verified: true,
    description:
      "MacBook Pro 16-inch with M1 chip. Brand new unit with warranty and original packaging.",
    category: 4,
  },
  {
    id: 10,
    title: "Wooden Desk Chair",
    price: 8500,
    location: "Addis Ababa, Nifas Silk",
    image: "/images/wooden-desk-chair.jpg",
    condition: "Used",
    seller: "Furniture Hub",
    rating: 4.5,
    category: 5,
  },
  {
    id: 11,
    title: "1 Bedroom Apartment Near ASTU Campus",
    price: 4500,
    location: "Adama, ASTU Area",
    image: "/placeholder.svg",
    condition: "Like New",
    seller: "Hanna M.",
    rating: 4.7,
    description: "Furnished room near campus gate. Water and Wi-Fi included. Ideal for students.",
    category: 2,
  },
  {
    id: 12,
    title: "Organic Face Cream Set",
    price: 650,
    location: "Addis Ababa, Bole",
    image: "/placeholder.svg",
    condition: "Brand New",
    seller: "Beauty Corner",
    verified: true,
    rating: 4.9,
    category: 7,
  },
  {
    id: 13,
    title: "Laptop Repair & Formatting Service",
    price: 500,
    location: "ASTU Campus, Adama",
    image: "/placeholder.svg",
    condition: "Brand New",
    seller: "TechFix ASTU",
    rating: 5.0,
    description: "Fast laptop repair, OS installation, and virus removal for students.",
    category: 8,
  },
  {
    id: 14,
    title: "Engineering Textbooks Bundle",
    price: 1200,
    location: "ASTU Campus, Adama",
    image: "/placeholder.svg",
    condition: "Used",
    seller: "Abebe Tadesse",
    rating: 4.8,
    description: "Calculus, Physics, and Programming textbooks. Good condition with minimal notes.",
    category: 4,
  },
];

export function getCategoryName(categoryId: number): string {
  return CATEGORIES.find((c) => c.id === categoryId)?.name ?? "General";
}

export const USER_TYPES = {
  BUYER: "buyer",
  SELLER: "seller",
} as const;
